<?xml version="1.0" encoding="utf-8"?><Database Name="BeursFuifLicenses" EntityNamespace="DataBase" ContextNamespace="DataBase" Class="LicenseDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=BeursFuifLicenses;Integrated Security=True" SettingsObjectName="LicenseServerImplementation.Properties.Settings" SettingsPropertyName="BeursFuifLicensesConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LicenseRequest" Member="LicenseRequests">
    <Type Name="LicenseRequest">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LicenseID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[Log]" Member="Logs">
    <Type Name="Log">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinutesLeft" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(590)" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LogDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.License" Member="Licenses">
    <Type Name="License">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Hours" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ActivationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ActivationIP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TestLicense" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ResetLicense" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ImagePath" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BeursEvent" Member="BeursEvents">
    <Type Name="BeursEvent">
      <Column Name="BeursEventID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="StreetNumber" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DrinkOrder" Member="DrinkOrders">
    <Type Name="DrinkOrder">
      <Column Name="DrinkOrderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="DrinkID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BeursEventID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DrinkName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Drink" Member="Drinks">
    <Type Name="Drink">
      <Column Name="DrinkID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Token" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="BeursEventID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="DrinkName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPrice" Type="System.Decimal" DbType="Decimal(9,2) NOT NULL" CanBeNull="false" />
      <Column Name="NextPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="NextManualPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="MinPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="MaxPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="NormalPrice" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Column Name="Hotkey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>